### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by jurgenhaas** [jceb/mdshow#2]
This is an awesome project, thanks for making this available. I've tried this today on Ubuntu 18.04 and ran into a couple of smaller issues which I'd like to report so that you can probably fix them for the future:

- the prerequisite yarn is not documented
- global node packages gulp-connect and yargs don't get installed automatically, I had to install them manually
- when running `mdshow serve`, I'm getting this error:

```
cd /home/jurgenhaas/.config/mdshow/reveal.js && yarn gulp -f mdshow-gulp.js --port=3000 --slides="slides.md" --root="/home/jurgenhaas/Downloads/mdshow/test1/.build"
yarn run v1.22.5
error Command "gulp" not found.
```

When I look into `/home/jurgenhaas/.config/mdshow/reveal.js/package.json` there is no script called `gulp`, so when I instead manually call `yarn build -f mdshow-gulp.js --port=3000 --slides="slides.md" --root="/home/jurgenhaas/Downloads/mdshow/test1/.build"`, then it works just fine.

**Comment by qx-775** [comment]
Attempt 2 to try to run mdshow.
I can only use `sudo ./mdshow serve` to run the webserver on port 3000
I probably should not use sudo though..
After that i see `Cannot GET /` on the webpage.
The console logs the following:

`127.0.0.1/:1 Refused to load the script 'http://127.0.0.1:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
`
I tried adding `<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' http://* 'unsafe-inline'; script-src 'self' http://* 'unsafe-inline' 'unsafe-eval'" />
` 

to `index.html` but still was unsuccessful. What can I do?

**Comment by jceb** [comment]
@qx-775 thanks for reporting the issue. I'm afraid there's something else broken. You shouldn't need sudo.

@jurgenhaas thank you for the feedback. I'll have a look and correct the documentation/add the dependencies. Feel free to also hand in PRs, I'm happy to accept them.

**Comment by jurgenhaas** [comment]
Following my experience in #3 it turned out that using yarn caused a couple of issues and using npm instead, fixed the issue. So I'm closing this one now.
